// angular/ChromelyAngular/ChromelyAngularCefGlue/angularapp/src/app/home/home.component.ts
import { Component } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent {

  constructor(private router: Router, private actRouter: ActivatedRoute) {
  }

  showInfoTestPanel(): void {
    this.router.navigateByUrl("/infotests");
  }
}

<div>
  <div class="col-12">
    <div class="centerBlock">
      <div class="row">
        <div class="col">
          <img src="../content/img/chromely.png" class="img-rounded" alt="Chromely Logo" width="200" height="200" style='margin-top: 20px;'>
        </div>
        <div class="col">
          <img width="240" height="240" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
        </div>
      </div>

      <span class="text-primary text-center"><h2>chromely + angular</h2></span>
      <p class="text-muted text-center">Build .NET/.NET CORE HTML5 Desktop Apps</p>
    </div>
  </div>

  <div class="col-12" style='padding:20px;'>
    <div id="runButton" class="centerBlock">
      <form class="form-inline">
        <div class="form-group">
          <label for="info">Message Router/Ajax Demos:</label>
        </div>
        <button id="buttonDemoRun" type="button" class="btn btn-primary" (click)="showInfoTestPanel()" style='margin: 5px;'>Run</button>
      </form>
    </div>
  </div>

</div>

// angular-react-vue/ChromelyVueCefSharp/vueapp/src/Home.vue
<template>
<div>
  <div class="col-12">
    <div class="centerBlock">
      <div class="row">
        <div class="col">
          <img src="./assets/img/chromely.png" class="img-rounded" alt="Chromely Logo" width="200" height="200" style='margin-top: 20px;' />
        </div>
        <div class="col">
             <img src="./assets/img/logo.png" class="img-rounded" alt="Vue Logo" width="200" height="200" style='margin-top: 20px;' />
        </div>
      </div>

      <span class="text-primary text-center"><h2>chromely + vue</h2></span>
      <p class="text-muted text-center">Build .NET/.NET CORE HTML5 Desktop Apps</p>
    </div>
  </div>

  <div class="col-12" style='padding:20px;'>
    <div id="runButton" class="centerBlock">
      <form class="form-inline">
        <div class="form-group">
          <label for="info">RegisterAsyncJsObject/Http Demos:</label>
        </div>
        <router-link to="/demo"> <button id="buttonDemoRun" type="button" class="btn btn-primary" style='margin: 5px;'>Run</button></router-link>
      </form>
    </div>
  </div>

</div>
</template>

<script>
  export default {

  }
</script>
