// angular-react-vue/ChromelyVueCefSharp/vueapp/src/Home.vue
<template>
<div>
  <div class="col-12">
    <div class="centerBlock">
      <div class="row">
        <div class="col">
          <img src="./assets/img/chromely.png" class="img-rounded" alt="Chromely Logo" width="200" height="200" style='margin-top: 20px;' />
        </div>
        <div class="col">
             <img src="./assets/img/logo.png" class="img-rounded" alt="Vue Logo" width="200" height="200" style='margin-top: 20px;' />
        </div>
      </div>

      <span class="text-primary text-center"><h2>chromely + vue</h2></span>
      <p class="text-muted text-center">Build .NET/.NET CORE HTML5 Desktop Apps</p>
    </div>
  </div>

  <div class="col-12" style='padding:20px;'>
    <div id="runButton" class="centerBlock">
      <form class="form-inline">
        <div class="form-group">
          <label for="info">RegisterAsyncJsObject/Http Demos:</label>
        </div>
        <router-link to="/demo"> <button id="buttonDemoRun" type="button" class="btn btn-primary" style='margin: 5px;'>Run</button></router-link>
      </form>
    </div>
  </div>

</div>
</template>

<script>
  export default {

  }
</script>

// angular-react-vue/ChromelyReactCefSharp/reactapp/src/Home.js
import React from 'react'
import { Link } from 'react-router-dom'
import { Container, Row, Col, Label, Media } from 'reactstrap';

const chromelylogo = require('./assets/img/chromely.png');
const reactlogo = require('./assets/img/logo.svg');

const Home = () => (

    <Container>
      <div className="centerBlock">
       <Row>
           <Col xs="2">
           </Col>
           <Col xs="4">
            <Media object src={chromelylogo} className="img-rounded" alt="Chromely Logo" width="200" height="200">
            </Media>
          </Col>
          <Col xs="4">
              <Media  object src={reactlogo} className="react-logo" alt="react logo" width="240" height="240" >
            </Media>
          </Col>
          <Col xs="2">
          </Col>
        </Row>

        <Row className="centerBlock">
          <span className="text-primary text-center"><h2>chromely + reactjs</h2></span>
        </Row>

        <Row className="centerBlock">
           <p className="text-muted text-center">Build .NET/.NET CORE HTML5 Desktop Apps</p>
        </Row>

        <Row className="centerBlock">
            <Label for="info">RegisterAsyncJsObject/Http Demos:</Label>
             <Link to="/demo"><button id="buttonDemoRun"  className="btn btn-primary" style={{margin: '5px'}}>Run</button></Link>
        </Row>

  </div>

</Container>
)

export default Home
